version: 2
registries:
  docker-registry:
    type: docker-registry
    url: ghcr.io
    username: ${{ github.actor }}
    password: ${{ secrets.GHCR_PAT }}
  sevan-packagr:
    type: python-index
    url: https://api.packagr.app/EYvhW6SyL
    username: ${{secrets.PACKAGR_USERNAME}}
    password: ${{secrets.PACKAGR_PASSWORD}}
updates:
  - package-ecosystem: "pip"
    directory: "/"
    insecure-external-code-execution: allow
    registries:
      - sevan-packagr
      - docker-registry
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
