version: 2
registries:
  sevan-packagr:
    type: python-index
    url: https://api.packagr.app/EYvhW6SyL
    username: ${{secrets.PACKAGR_USERNAME}}
    password: ${{secrets.PACKAGR_PASSWORD}}
updates:
  - package-ecosystem: "pip"
    directory: "/"
    registries:
      - sevan-packagr
    schedule:
      interval: "weekly"
