from modeltestSDK import SDKclient, Campaign

restrict_access = True

position1 = {'x': 310.70, 'y': 0, 'z': 0}
position2 = {'x': 0, 'y': 0, 'z': 0}
position3 = {'x': 0, 'y': -310.70, 'z': 0}

positionBOW = {'x': 17.5, 'y': -30, 'z': -72}
positionWL = {'x': 0, 'y': 0, 'z': -30}


pos_BL = {'x': 0, 'y': 0, 'z': 0}

 #TODO: Add tags, update desc, update coords

def add_sensors(campaign: Campaign, client: SDKclient):
    sensor = client.sensor.create(name="WAVE_1",
                                  description="Wave elevation 350 m ahead of midship",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="WAVE_3",
                                  description="Wave elevation 350 m port of midship",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    '''sensor = client.sensor.create(name="CURRENT_2",
                                  description="Current velocity 360m ahead of FPU",
                                  unit="m/s",
                                  kind="velocity",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)'''  # Potential duplicate

    sensor = client.sensor.create(name="WIND_Ui",
                                  description="Wind velocity, power on fans in Volt",
                                  unit="V",
                                  kind="control signal",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="PRESS_TOP_6639",
                                  description="Water pressure on top damping plate",
                                  unit="bar",
                                  kind="pressure",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="PRESS_TOP_6635",
                                  description="Water pressure on bottom damping plate",
                                  unit="bar",
                                  kind="pressure",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="REL_WAVE_0",
                                  description="Relative waveheight at LQ – 0 deg",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="REL_WAVE_120",
                                  description="Relative waveheight at 120 deg",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="REL_WAVE_270",
                                  description="Relative waveheight transverse LQ – 270deg",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="REL_WAVE_300",
                                  description="Relative waveheight at 300 deg",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="REL_WAVE_MOONP_CENTRE",
                                  description="Relative waveheight at centre moonpool",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="REL_WAVE_MOONP_120",
                                  description="Relative waveheight in moonpool at 120deg",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="REL_WAVE_MOONP_300",
                                  description="Relative waveheight in moonpool at 300deg",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="GREEN_WATER_300_1",
                                  description="Green water on P-deck at 300 deg, pos 1",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="GREEN_WATER_300_2",
                                  description="Green water on P-deck at 300 deg, pos 2",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="GREEN_WATER_300_3",
                                  description="Green water on P-deck at 300 deg, pos 3",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="X_ACC_MOONP_C",
                                  description="X-acceleration at MOONPOOL_CENTRE",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="Y_ACC_MOONP_C",
                                  description="Y-acceleration at MOONPOOL_CENTRE",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="Z_ACC_MOONP_C",
                                  description="Z-acceleration at MOONPOOL_CENTRE",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="X_ACC_PDK_120",
                                  description="X-acceleration at P-deck at 120 deg",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="Y_ACC_PDK_120",
                                  description="Y-acceleration at P-deck at 120 deg",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="Z_ACC_PDK_120",
                                  description="Z-acceleration at P-deck at 120 deg",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="FZ_PONTOON",
                                  description="Vertical force on pontoon element at 300deg",
                                  unit="kN",
                                  kind="force",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="M_300_PONTOON",
                                  description="Moment on pontoon element at 300 deg",
                                  unit="kNm",
                                  kind="moment",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="TENSION_01",
                                  description="Tension in line 1 of FPU",
                                  unit="kN",
                                  kind="force",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="TENSION_02",
                                  description="Tension in line 2 of FPU",
                                  unit="kN",
                                  kind="force",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="TENSION_05",
                                  description="Tension in line 5 of FPU",
                                  unit="kN",
                                  kind="force",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="TENSION_06",
                                  description="Tension in line 6 of FPU",
                                  unit="kN",
                                  kind="force",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="TENSION_09",
                                  description="Tension in line 9 of FPU",
                                  unit="kN",
                                  kind="force",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="TENSION_10",
                                  description="Tension in line 10 of FPU",
                                  unit="kN",
                                  kind="force",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="TENSION_R01",
                                  description="Tension in riser 01 of FPU",
                                  unit="kN",
                                  kind="force",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="X_POS_BL",
                                  description="X-position at BL line and centre",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="Y_POS_BL",
                                  description="Y-position at BL line and centre",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="Z_POS_BL",
                                  description="Z-position at BL line and centre",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="X_POS_WL",
                                  description="X-position at WL line and centre",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="Y_POS_WL",
                                  description="Y-position at WL line and centre",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="Z_POS_WL",
                                  description="Z-position at WL line and centre",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="ROLL",
                                  description="Roll motion of FPU",
                                  unit="deg",
                                  kind="angle",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="PITCH",
                                  description="Pitch motion of FPU",
                                  unit="deg",
                                  kind="angle",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="YAW",
                                  description="Yaw motion of FPU",
                                  unit="deg",
                                  kind="angle",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="XY_POS_WL",
                                  description="XY-position at WL line and centre",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="XPOS_MOONP_C",
                                  description="X-position at MOONPOOL_CENTRE",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="YPOS_MOONP_C",
                                  description="Y-position at MOONPOOL_CENTRE",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="ZPOS_MOONP_C",
                                  description="Z-position at MOONPOOL_CENTRE",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="XPOS_PDCK_BOW",
                                  description="X-position at PROCESS_DECK_BOW",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="YPOS_PDCK_BOW",
                                  description="Y-position at PROCESS_DECK_BOW",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="ZPOS_PDCK_BOW",
                                  description="Z-position at PROCESS_DECK_BOW",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="XPOS_PDCK_STERN",
                                  description="X-position at PROCESS_DECK_STERN",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="YPOS_PDCK_STERN",
                                  description="Y-position at PROCESS_DECK_STERN",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="ZPOS_PDCK_STERN",
                                  description="Z-position at PROCESS_DECK_STERN",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="XPOS_HELID",
                                  description="X-position at HELIDECK",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="YPOS_HELID",
                                  description="Y-position at HELIDECK",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="ZPOS_HELID",
                                  description="Z-position at HELIDECK",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="XACC_MOONP_C_CALC",
                                  description="X-acceleration at MOONPOOL_CENTRE. Derived from motion measurements",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="YACC_MOONP_C_CALC",
                                  description="Y-acceleration at MOONPOOL_CENTRE. Derived from motion measurements",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="ZACC_MOONP_C_CALC",
                                  description="Z-acceleration at MOONPOOL_CENTRE. Derived from motion measurements",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,)

    sensor = client.sensor.create(name="XACC_PDCK_BOW_CALC",
                                  description="X-acceleration at P-deck at 300 deg",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="YACC_PDCK_BOW_CALC",
                                  description="Y-acceleration at P-deck at 300 deg",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="ZACC_PDCK_BOW_CALC",
                                  description="Z-acceleration at P-deck at 300 deg",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,)

    sensor = client.sensor.create(name="XACC_PDCK_STERN_CALC",
                                  description="X-acceleration at P-deck at 120 deg",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="YACC_PDCK_STERN_CALC",
                                  description="Y-acceleration at P-deck at 120 deg",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="ZACC_PDCK_STERN_CALC",
                                  description="Z-acceleration at P-deck at 120 deg",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)
    '''
    sensor = client.sensor.create(name="XACC_HELIDECK",
                                  description="",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="YACC_HELIDECK",
                                  description="",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="ZACC_HELIDECK",
                                  description="",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access) ''' # Not found in final report

    sensor = client.sensor.create(name="WAVE_1_CAL",
                                  description="Calib. wave elev. 350 m ahead of model",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="WAVE_2_CAL",
                                  description="Calib. wave elevation at midship",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="WAVE_3_CAL",
                                  description="Calib. wave elev. 350 m port side of model",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="XVEL_MOONPOOL",
                                  description="Water velocity at centre of moonpool at BL",
                                  unit="m/s",
                                  kind="velocity",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="ZVEL_MOONPOOL",
                                  description="Water velocity at centre of moonpool at BL",
                                  unit="m/s",
                                  kind="velocity",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="CURRENT_1",
                                  description="Current velocity at 14m depth at FPU",
                                  unit="m/s",
                                  kind="velocity",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="CURRENT_2",
                                  description="Current at 24 m depth 420 m ahead of FPU",
                                  unit="m/s",
                                  kind="velocity",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="WIND_SPEED",
                                  description="Wind velocity at FPU model",
                                  unit="m/s",
                                  kind="velocity",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    '''sensor = client.sensor.create(name="SLAM_39.5_300",
                                  description="Square slamming panel (2.8*2.8)",
                                  unit="kN",
                                  kind="slamming force",
                                  area = "7.8",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="SLAM_43.5_300",
                                  description="Square slamming panel (2.8*2.8)",
                                  unit="kN",
                                  kind="slamming force",
                                  area = "7.8",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="SLAM_47.5_300",
                                  description="Square slamming panel (2.8*2.8)",
                                  unit="kN",
                                  kind="slamming force",
                                  area = "7.8",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="SLAM_43.5_310",
                                  description="Square slamming panel (2.8*2.8)",
                                  unit="kN",
                                  kind="slamming force",
                                  area = "7.8",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)'''

    sensor = client.sensor.create(name="FX_WIND_CURR",
                                  description="Current/ wind force in X-direction",
                                  unit="kN",
                                  kind="force",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="FY_WIND_CURR", # TODO Rapport named FX
                                  description="Current/ wind force in Y-direction",
                                  unit="kN",
                                  kind="force",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="MZ_WIND_CURR",
                                  description="Current/ wind turning moment about centre",
                                  unit="kNm",
                                  kind="moment",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="PULLOUT_FORCE",
                                  description="Tension in pull line",
                                  unit="kN",
                                  kind="force",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="XPOS_BL_WAVEDIR",
                                  description="X-position at BL line and centre",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="YPOS_BL_WAVEDIR",
                                  description="Y-position at BL line and centre",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="ZPOS_BL_WAVEDIR",
                                  description="Z-position at BL line and centre",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="XPOS_WL_WAVEDIR",
                                  description="X-position at WL line and centre",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="YPOS_WL_WAVEDIR",
                                  description="Y-position at WL line and centre",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="ZPOS_WL_WAVEDIR",
                                  description="Z-position at WL line and centre",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="XPOS_HELID_WAVEDIR",
                                  description="X-position at HELID",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="YPOS_HELID_WAVEDIR",
                                  description="Y-position at HELID",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="ZPOS_HELID_WAVEDIR",
                                  description="Z-position at HELID",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="XPOS_MOONP_C_WAVEDIR",
                                  description="X-position at MOONPOOL_CENTRE",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="YPOS_MOONP_C_WAVEDIR",
                                  description="Y-position at MOONPOOL_CENTRE",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="ZPOS_MOONP_C_WAVEDIR",
                                  description="Z-position at MOONPOOL_CENTRE",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="XPOS_PDCK_STERN_WAVEDIR",
                                  description="X-position at PDCK_STERN",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="YPOS_PDCK_STERN_WAVEDIR",
                                  description="Y-position at PDCK_STERN",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="ZPOS_PDCK_STERN_WAVEDIR",
                                  description="Z-position at PDCK_STERN",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="XPOS_PDCK_BOW_WAVEDIR",
                                  description="X-position at PDCK_BOW",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="YPOS_PDCK_BOW_WAVEDIR",
                                  description="Y-position at PDCK_BOW",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="ZPOS_PDCK_BOW_WAVEDIR",
                                  description="Z-position at PDCK_BOW",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="XY_POS_WL_WAVEDIR",
                                  description="XY-position at WL line and centre",
                                  unit="m",
                                  kind="length",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=False,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="ROLL_WAVEDIR",
                                  description="Roll motion of FPU",
                                  unit="deg",
                                  kind="angle",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="PITCH_WAVEDIR",
                                  description="Pitch motion of FPU",
                                  unit="deg",
                                  kind="angle",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="YAW_WAVEDIR",
                                  description="Yaw motion of FPU",
                                  unit="deg",
                                  kind="angle",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="X_ACC_MOONP_C_WAVEDIR",
                                  description="X-acceleration at MOONPOOL_CENTRE",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="Y_ACC_MOONP_C_WAVEDIR",
                                  description="Y-acceleration at MOONPOOL_CENTRE",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="Z_ACC_MOONP_C_WAVEDIR",
                                  description="Z-acceleration at MOONPOOL_CENTRE",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="X_ACC_PDCK_STERN_WAVEDIR",
                                  description="X-acceleration at P-deck at 120 deg",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="Y_ACC_PDCK_STERN_WAVEDIR",
                                  description="Y-acceleration at P-deck at 120 deg",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="Z_ACC_PDCK_STERN_WAVEDIR",
                                  description="Z-acceleration at P-deck at 120 deg",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="X_ACC_PDCK_BOW_WAVEDIR",
                                  description="X-acceleration at P-deck at 300 deg",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="Y_ACC_PDCK_BOW_WAVEDIR",
                                  description="Y-acceleration at P-deck at 300 deg",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)

    sensor = client.sensor.create(name="Z_ACC_PDCK_BOW_WAVEDIR",
                                  description="Z-acceleration at P-deck at 300 deg",
                                  unit="m/s^2",
                                  kind="acceleration",
                                  x=position1['x'],
                                  y=position1['y'],
                                  z=None,
                                  is_local=True,
                                  campaign_id=campaign.id,
                                  read_only=restrict_access)




