version: "3"
services:
  sut:
    build:
      context: .
      dockerfile: tests.Dockerfile
    depends_on:
      - db
      - api
    command: pytest tests/
    links:
      - "api"
    ports:
      - "5000:8080"
    networks:
      - frontend
  api:
    image: ghcr.io/sevanssp/inquire_modeltest:latest
    command: gunicorn -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080 --access-logfile - --error-logfile - app.main:app
    environment:
      - INQUIRE_MODELTEST_DATABASE_URI=postgresql+psycopg2://postgres:postgres@db:5432/test
      - ADMINISTRATOR_KEY=administrator
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    depends_on:
      - db
    networks:
      - frontend
      - backend
    ports:
      - "5000:8080"
    expose:
      - 5000
  db:
    image: postgres:10
    networks:
      - backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "8001:5432"
    volumes:
      - ./docker_scripts:/docker-entrypoint-initdb.d
      - app-db-data:/var/lib/postgresql/data/pgdata
volumes:
  app-db-data:

networks:
  frontend:
  backend:
