site_name: Inquire Model Test SDK, by Sevan
nav:
  - Home: 'index.md'
  - Coordinates: 'coordinates.md'
  - Examples: 'examples.md'
theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.instant
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: "examples/"
      check_paths: true
repo_url: https://github.com/SevanSSP/inquire-modeltest-sdk
copyright: Copyright &copy; 2021 Sevan SSP