site_name: Python SDK for the Sevan model test API
theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
  plugins:
    - search
  icon:
    repo: fontawesome/brands/github
nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Coordinates: 'coordinates.md'
  - Examples: 'examples.md'
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.snippets
repo_url: https://github.com/SevanSSP/inquire-modeltest-sdk