site_name: Sevan Model Test SDK Docs
theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: blue
  features:
    - navigation.instant
nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Examples: 'examples.md'
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences