[tool.poetry]
name = "modeltestSDK"
version = "1.3.13"
description = "SDK for use with modeltest API"
authors = ["Jørgen Engelsen <jen@sevanssp.com>","Per Voie <pev@sevanssp.com>", "Einar Glomnes <ebg@sevanssp.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/SevanSSP/inquire-modeltest-sdk"
packages = [{ include = "modeltestSDK" },]
include = [
    "LICENSE"
]

[tool.poetry.dependencies]
matplotlib="^3.1.1"
pandas="^1.2.1"
requests="^2.24.0"
scipy="^1.5.0"
python = "^3.6"



[tool.poetry.dev-dependencies]
nox = "^2020.8.22"

[[tool.poetry.source]]
name = "private_pypi"
url = "https://api.packagr.app/EYvhW6SyL/"

[tool.poetry.urls]
download = "https://api.packagr.app/EYvhW6SyL/"
issues = "https://github.com/SevanSSP/inquire-modeltest-sdk/issues"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
