[tool.poetry]
name = "modeltestSDK"
version = "2.2.4"
description = "SDK for use with modeltest API"
authors = ["Jørgen Engelsen <jen@sevanssp.com>","Per Voie <pev@sevanssp.com>", "Einar Glomnes <ebg@sevanssp.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/SevanSSP/inquire-modeltest-sdk"
packages = [{ include = "modeltestSDK" },]
include = [
    "LICENSE"
]

[tool.poetry.dependencies]
matplotlib = "^3.5.3"
pandas="^1.3.5"
requests="^2.28.1"
python = "^3.7.1"
pydantic = "^1.10.7"
requests-cache = "^1.0.1"


[tool.poetry.dev-dependencies]
pytest = "^7.3.0"
nox = "^2022.11.21"
scipy="^1.6.1"
jupyter="^1"
mkdocs = "1.4.2"
mkdocs-material = "^6.0.1"

[tool.poetry.urls]
download = "https://api.packagr.app/EYvhW6SyL/"
issues = "https://github.com/SevanSSP/inquire-modeltest-sdk/issues"

[build-system]
requires = ["poetry>=1.1.4"]
build-backend = "poetry.masonry.api"
