[tool.poetry]
name = "modeltestSDK"
version = "2.3.0"
description = "SDK for use with modeltest API"
authors = ["Jørgen Engelsen <jen@sevanssp.com>","Per Voie <pev@sevanssp.com>", "Einar Glomnes <ebg@sevanssp.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/SevanSSP/inquire-modeltest-sdk"
packages = [{ include = "modeltestSDK" },]
include = [
    "LICENSE"
]

[tool.poetry.dependencies]
matplotlib = "^3.7.2"
requests="2.31.0"
python = ">=3.8.0,<3.11"
pydantic = "^1.10.12,<2"
requests-cache = "^1.1.0"
qats = "^4.11.1"
pandas = ">=1,<2"

[tool.poetry.dev-dependencies]
pytest = "^7.3.0"
nox = "^2023.4.22"
scipy="^1.10.1"
jupyter="^1"
mkdocs = "1.4.3"
mkdocs-material = "^9.1.20"
coverage = "^7.2.5"
pytest-cov = "^4.1.0"
pytest-docker = "^2.0.0"

[tool.poetry.urls]
download = "https://api.packagr.app/EYvhW6SyL/"
issues = "https://github.com/SevanSSP/inquire-modeltest-sdk/issues"

[build-system]
requires = ["poetry>=1.1.4"]
build-backend = "poetry.masonry.api"
