[tool.poetry]
name = "modeltestSDK"
version = "2.2.0"
description = "SDK for use with modeltest API"
authors = ["Jørgen Engelsen <jen@sevanssp.com>","Per Voie <pev@sevanssp.com>", "Einar Glomnes <ebg@sevanssp.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/SevanSSP/inquire-modeltest-sdk"
packages = [{ include = "modeltestSDK" },]
include = [
    "LICENSE"
]

[tool.poetry.dependencies]
matplotlib = "^3.4.3"
pandas="^1.0.0"
requests="^2.24.0"
python = "^3.7.1"
pydantic = "^1.7.3"
requests-cache = "^0.8.1"


[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
nox = "^2020.8.22"
scipy="^1.5.0"
jupyter="^1"
mkdocs="^1.1"
mkdocs-material = "^6.0.1"

[[tool.poetry.source]]
name = "private_pypi"
url = "https://api.packagr.app/EYvhW6SyL/"

[tool.poetry.urls]
download = "https://api.packagr.app/EYvhW6SyL/"
issues = "https://github.com/SevanSSP/inquire-modeltest-sdk/issues"

[build-system]
requires = ["poetry>=1.1.4"]
build-backend = "poetry.masonry.api"
