[tool.poetry]
name = "modeltestsdk"
version = "3.1.2"
description = "SDK for use with modeltest API"
authors = ["Jørgen Engelsen","Per Voie", "Snorre Fjellvang <slf@sevanssp.com>", "Einar Glomnes <ebg@sevanssp.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/SevanSSP/inquire-modeltest-sdk"
packages = [{ include = "modeltestsdk" },]
include = [
    "LICENSE"
]

[tool.poetry.dependencies]
matplotlib = "^3.9"
requests="2.32.3"
python = ">=3.9,<3.13"
pydantic = "^2.8.2"
requests-cache = "^1.2.1"
qats = "^5"
pandas = "<2.3"
pydantic-settings = "^2.5.2"

[tool.poetry.group.dev.dependencies]
bandit = "^1.7.10"
pytest = "^8.3.3"
nox = "^2024.4.15"
scipy="^1.10.1"
jupyter="^1"
mkdocs = "1.6.0"
mkdocs-material = "^9.5.47"
coverage = "^7.6.1"
pytest-cov = "^5.0.0"
pytest-docker = "^3.1.1"

[tool.poetry.urls]
download = "https://api.packagr.app/EYvhW6SyL/"
issues = "https://github.com/SevanSSP/inquire-modeltest-sdk/issues"

[build-system]
requires = ["poetry>=1.8"]
build-backend = "poetry.masonry.api"
