[tool.poetry]
name = "hydra_radical"
version = "1.3.0"
description = "SDK for use with modeltest API"
authors = ["Jørgen Engelsen <jen@sevanssp.com>",Per Voie <pev@sevanssp.com>", "Einar Glomnes <ebg@sevanssp.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/SevanSSP/inquire-modeltest-sdk"
include = [
    "LICENSE"
]

[tool.poetry.scripts]
hydra-radical = "hydra_radical.cli:main"
hydra-radical-app = "hydra_radical.cli:launch_app"

[tool.poetry.dependencies]
atomicwrites = "1.4.0"
attrs = "19.3.0"
certifi = "2020.6.20"
chardet="3.0.4"
colorama="0.4.3"
coverage="5.1"
cycler="0.10.0"
idna="2.9"
importlib-metadata="1.6.1"
kiwisolver="1.2.0"
matplotlib="3.1.1"
more-itertools="8.4.0"
multidict="4.7.6"
numpy="1.19.0"
packaging="20.4"
pandas="0.25.3"
pluggy="0.13.1"
py="1.8.2"
pyparsing="2.4.7"
python-dateutil="2.8.1"
pytz="2020.1"
requests="2.24.0"
scipy="1.6.0"
six="1.15.0"
urllib3="1.25.9"
wcwidth="0.2.5"
yarl="1.4.2"
zipp="3.1.0+"
python = "^3.6"



[tool.poetry.dev-dependencies]
pytest="5.4.3"
pytest-cov="2.8.1"

[[tool.poetry.source]]
name = "private_pypi"
url = "https://api.packagr.app/EYvhW6SyL/"

[tool.poetry.urls]
download = "https://api.packagr.app/EYvhW6SyL/"
issues = "https://github.com/SevanSSP/inquire-modeltest-sdk/issues"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
