[tool.poetry]
name = "modeltestSDK"
version = "2.2.4"
description = "SDK for use with modeltest API"
authors = ["Jørgen Engelsen <jen@sevanssp.com>","Per Voie <pev@sevanssp.com>", "Einar Glomnes <ebg@sevanssp.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/SevanSSP/inquire-modeltest-sdk"
packages = [{ include = "modeltestSDK" },]
include = [
    "LICENSE"
]

[tool.poetry.dependencies]
matplotlib = "^3.5.3"
pandas="^2.0.3"
requests="^2.28.2"
python = ">=3.8.1,<3.12"
pydantic = "^1.10.7"
requests-cache = "^1.0.1"

[tool.poetry.dev-dependencies]
pytest = "^7.3.0"
nox = "^2023.4.22"
scipy="^1.10.1"
jupyter="^1"
mkdocs = "1.4.3"
mkdocs-material = "^9.1.14"
coverage = "^7.2.7"
pytest-cov = "^4.0.0"
pytest-docker = "^1.0.1"

[tool.poetry.urls]
download = "https://api.packagr.app/EYvhW6SyL/"
issues = "https://github.com/SevanSSP/inquire-modeltest-sdk/issues"

[build-system]
requires = ["poetry>=1.1.4"]
build-backend = "poetry.masonry.api"
