name: Publish Python package to Repoforge

on:
  release:
    types: [created, edited]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: pip install nox uv
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Run tests with Nox
      run: nox -s lint tests_github --verbose

    - name: Build package
      run: uv build

    - name: Publish package
      run: uv publish --publish-url https://api.repoforge.io/EYvhW6SyL/ --token ${REPOFORGE_TOKEN}
      env:
        REPOFORGE_TOKEN: ${{ secrets.REPOFORGE_TOKEN }}